image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 5672
- port: 15672

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - command: /opt/rabbitmq/sbin/rabbitmq-server &
  - command: rabbitmq-plugins enable rabbitmq_management
